### ISSUE TITLE
Typerror running chebpy

### ISSUE THREAD

**Issue by recifx** [chebpy/chebpy#9]
I have chebpy (installed from github) with Python 3.8.
On running the sample code from the README
```
from numpy import *
from matplotlib.pyplot import *
from chebpy import chebfun
x = chebfun('x', [0, 10])
f = sin(x) + sin(5*x)`
```
I am getting the following error 
```
 Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/numpy/core/function_base.py", line 117, in linspace
    num = operator.index(num)
TypeError: 'numpy.float64' object cannot be interpreted as an integer

```
Thanks for any assistance in resolving this issue.

**Comment by OrbitalMechanic** [comment]
I'm having a similar problem, except I'm running Python ver. 3.7.6 and get the message:

```
(base) user@Samuels-Mac-Pro ~ % python chebpy-ex.py
Traceback (most recent call last):
  File "/Users/user/opt/anaconda3/lib/python3.7/site-packages/numpy/core/function_base.py", line 117, in linspace
    num = operator.index(num)
TypeError: 'numpy.float64' object cannot be interpreted as an integer

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "chebpy-ex.py", line 6, in <module>
    f = sin(x) + sin(5*x)
  File "/Users/user/opt/anaconda3/lib/python3.7/site-packages/chebpy-0.1.0-py3.7.egg/chebpy/core/decorators.py", line 51, in wrapper
  File "/Users/user/opt/anaconda3/lib/python3.7/site-packages/chebpy-0.1.0-py3.7.egg/chebpy/core/chebfun.py", line 401, in method
  File "/Users/user/opt/anaconda3/lib/python3.7/site-packages/chebpy-0.1.0-py3.7.egg/chebpy/core/chebfun.py", line 401, in <listcomp>
  File "/Users/user/opt/anaconda3/lib/python3.7/site-packages/chebpy-0.1.0-py3.7.egg/chebpy/core/decorators.py", line 51, in wrapper
  File "/Users/user/opt/anaconda3/lib/python3.7/site-packages/chebpy-0.1.0-py3.7.egg/chebpy/core/classicfun.py", line 258, in method
  File "/Users/user/opt/anaconda3/lib/python3.7/site-packages/chebpy-0.1.0-py3.7.egg/chebpy/core/classicfun.py", line 58, in initfun_adaptive
  File "/Users/user/opt/anaconda3/lib/python3.7/site-packages/chebpy-0.1.0-py3.7.egg/chebpy/core/chebtech.py", line 55, in initfun
  File "/Users/user/opt/anaconda3/lib/python3.7/site-packages/chebpy-0.1.0-py3.7.egg/chebpy/core/chebtech.py", line 72, in initfun_adaptive
  File "/Users/user/opt/anaconda3/lib/python3.7/site-packages/chebpy-0.1.0-py3.7.egg/chebpy/core/algorithms.py", line 214, in adaptive
  File "/Users/user/opt/anaconda3/lib/python3.7/site-packages/chebpy-0.1.0-py3.7.egg/chebpy/core/algorithms.py", line 198, in standard_chop
  File "<__array_function__ internals>", line 6, in linspace
  File "/Users/user/opt/anaconda3/lib/python3.7/site-packages/numpy/core/function_base.py", line 121, in linspace
    .format(type(num)))
TypeError: object of type <class 'numpy.float64'> cannot be safely interpreted as an integer.
(base) user@Samuels-Mac-Pro ~ %
```

Where the code I ran was

```
#!/Users/user/opt/anaconda3/bin/python
from numpy import *
from matplotlib.pyplot import *
from chebpy import chebfun
x = chebfun('x', [0, 10])
f = sin(x) + sin(5*x)
```
Please advise.

Sam Dupree.

**Comment by OrbitalMechanic** [comment]
I did some additional investigating and found that the version of chebpy hosted at [https://pypi.org/project/chebpy/](https://pypi.org/project/chebpy/) seems to work, but for the test codes provided. However, the example I cited in my posting still does not work, because "chebfun" cannot be imported from chebpy.

Please advise & hope this helps.

Sam Dupree.

**Comment by OrbitalMechanic** [comment]
Here is a step-by-step procedure that allowed me to solve the TypeError problem with chebpy.

`1. Manually rebuilt the subdirectory /Users/user/opt/anaconda3/lib/python3.7/site-packages/chebpy-0.1.0-py3.7.egg. The install procedure built subdirectory as a document as opposed to an actual subdirectory.`

`2. Replaced the argument j2 with num=int(j2) in the function call linspace on line 198 in the file algorithms.py to num=int(j2). See attached file, algorithms.py.txt.`

`3. Modified the example (see file chebpy-ex.py.txt) posted on [https://github.com/chebpy/chebpy](https://github.com/chebpy/chebpy) to comply with Python 3.7.x.`

Please let me know if there is something I may have missed or other errors I may have introduced.

Hope this helps.

Sam Dupree.

[algorithms.py.txt](https://github.com/chebpy/chebpy/files/4620165/algorithms.py.txt)
[chebpy-ex.py.txt](https://github.com/chebpy/chebpy/files/4620166/chebpy-ex.py.txt)

**Comment by markrichardson** [comment]
@OrbitalMechanic Thanks for the thinking on this. One thing I should point out is the PyPi chebpy is not the same as this chebpy. As for the TypeError fix, if you're able to work this into a pull request, I'll be very happy to take a look.

**Comment by janniklasrose** [comment]
Just ran into the same TypeError and I think I found the fix, see my PR.

**Comment by markrichardson** [comment]
Tests still look good so have merged - thanks for looking at this @janniklasrose 

@recifx @OrbitalMechanic does this fix the issue for you as you see it?
